spring:
  thymeleaf:
    cache: false
  application:
    name: front
  config:
    import: optional:configserver:https://book1lluwa.store/config/
  security:
    oauth2:
      client:
        registration:
          payco:
            client-id: 3RDZIlUpl7bOHKX6p0kxxbg
            client-secret: v0DzVGayvD0POlxgNJ8AdKgU
            client-name: PAYCO
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile
        provider:
          payco:
            authorization-uri: https://id.payco.com/oauth2.0/authorize
            token-uri: https://id.payco.com/oauth2.0/token
            user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json
            user-name-attribute: id

logging:
  level:
      org.springframework.security.oauth2.client.endpoint.DefaultAuthorizationCodeTokenResponseClient: DEBUG
      org.springframework.web.client.RestTemplate: DEBUG