spring:
  application:
    name: front-service
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team1_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be10_team1
    password: N(zwIEW9ge2O3yXO
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

server:
  port: 8080

api:
  base-url: http://localhost:8081