spring:
  application:
    name: illuwa
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team1_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be10_team1
    password: N(zwIEW9ge2O3yXO
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

server:
  port: 10300
  address: 0.0.0.0